"""Stage a recovered zone into LSB.

Generates the minimum scaffolding to bring a cut/unused zone online:
  - SQL: zone_settings UPSERT (UPDATE if a placeholder row exists, else INSERT)
  - Lua: scripts/zones/<Name>/Zone.lua skeleton with onInitialize/onZoneIn
  - Lua: scripts/zones/<Name>/IDs.lua placeholder (text table empty)
  - Lua: scripts/enum/zone.lua patch line (printed, not written — single-line
    insert into an alphabetized enum is risky to automate)
  - GM warp: `!exec` command printed to stdout for in-game verification

Output mode:
  --dry-run  : print everything, write nothing (default if no --apply)
  --apply    : write Lua files; SQL is always printed (you decide when to run it)
"""

from __future__ import annotations

import re
import time
from pathlib import Path
from textwrap import dedent

import click

from xi.ftable.xi_core import load_all_tables, scan_file_ids
from xi.xi_config import FFXI_DIR
from xi.zone.xi_list import ZONE_NAME_DAT, parse_dmsg, zone_file_id

from xi.misc.xi_lsb import (
    PLACEHOLDER_NAMES,
    existing_zone_script_dirs,
    load_lsb_zone_enum,
    load_lsb_zones,
    lsb_root,
)


def _sanitize_name(raw: str) -> tuple[str, str]:
    """Return (folder_name, enum_name) for a human-given zone name.

    folder_name uses underscores (matching LSB convention: 'Aht_Urhgan_Whitegate').
    enum_name is UPPER_SNAKE_CASE for the xi.zone enum.
    """
    base = re.sub(r"[^A-Za-z0-9 _-]+", "", raw).strip()
    folder = base.replace(" ", "_")
    enum = re.sub(r"[^A-Z0-9_]", "", folder.upper().replace("-", "_"))
    return folder, enum


_ZONE_SETTINGS_ROW_RE = re.compile(
    r"^INSERT\s+INTO\s+`?zone_settings`?\s+VALUES\s*\(\s*(\d+)\s*,",
    re.IGNORECASE | re.MULTILINE,
)


def _sql_for(zone_id: int, folder_name: str, existing_row: bool) -> str:
    """Generate either an UPDATE (existing placeholder row) or an INSERT.

    Schema per sql/zone_settings.sql:
      zoneid, zonetype, zoneip, zoneport, name,
      music_day, music_night, battlesolo, battlemulti,
      restriction, tax, misc
    zonetype defaults to ZONE_TYPE::OUTDOORS (2) — see src/map/zone.h.
    Ops can change post-stage if the zone is a city/dungeon/instance/etc.
    """
    name_sql = folder_name.replace("'", "''")
    if existing_row:
        return (
            f"-- Promote placeholder row to a real zone\n"
            f"UPDATE `zone_settings` SET name='{name_sql}' WHERE zoneid={zone_id};\n"
        )
    return (
        f"-- Insert new zone row.\n"
        f"-- NOTE: zoneport defaults to 54230 (the LSB stock default). If you're\n"
        f"-- running a multi-process map setup (commonly ports 54330-54344),\n"
        f"-- you MUST update this row to one of the live ports before !zone will\n"
        f"-- find a host process. Z15 (54344) is the 'Instanced' catch-all and is\n"
        f"-- the recommended landing spot for recovery/sandbox zones.\n"
        f"INSERT INTO `zone_settings` "
        f"(zoneid, zonetype, zoneip, zoneport, name, music_day, music_night, battlesolo, battlemulti, restriction, tax, misc) "
        f"VALUES ({zone_id}, 2, '127.0.0.1', 54230, '{name_sql}', 0, 0, 0, 0, 0, 0.00, 0);\n"
        f"-- zonetype=2 (ZONE_TYPE::OUTDOORS); change to 1=CITY, 4=DUNGEON, 0x100=INSTANCED as needed\n"
        f"-- Quick host-process assignment (uncomment + change port to match your layout):\n"
        f"-- UPDATE `zone_settings` SET zoneport = 54344 WHERE zoneid = {zone_id};\n"
    )


_ZONE_LUA_TEMPLATE = dedent("""\
-----------------------------------
-- Zone: {folder_name} ({zone_id})
-- Recovered from client DAT {dat_path}
-- Generated by `xi misc stage` on {timestamp}
-----------------------------------
---@type TZone
local zoneObject = {{}}

zoneObject.onInitialize = function(zone)
    -- TODO: register trigger areas, spawn helpers, etc.
end

zoneObject.onZoneIn = function(player, prevZone)
    -- TODO: set spawn position; default below is the world origin.
    if player:getXPos() == 0 and player:getYPos() == 0 and player:getZPos() == 0 then
        player:setPos(0, 0, 0, 0)
    end
    return -1
end

zoneObject.onZoneOut = function(player) end
zoneObject.onRegionEnter = function(player, region) end
zoneObject.onRegionLeave = function(player, region) end
zoneObject.onEventUpdate = function(player, csid, option, npc) end
zoneObject.onEventFinish = function(player, csid, option, npc) end

return zoneObject
""")

_IDS_LUA_TEMPLATE = dedent("""\
-----------------------------------
-- Area: {folder_name}
-----------------------------------
zones = zones or {{}}

zones[xi.zone.{enum_name}] =
{{
    text = {{}},
    mob  = {{}},
    npc  = {{}},
}}

return zones[xi.zone.{enum_name}]
""")


def stage(
    zone_id: int,
    pretty_name: str,
    apply: bool,
) -> dict:
    folder_name, enum_name = _sanitize_name(pretty_name)
    root = lsb_root()

    # Look up DAT for the report.
    tables = load_all_tables()
    hits = scan_file_ids([zone_file_id(zone_id)], tables)
    dat_path = hits[0]["dat"] if hits else "<no DAT>"

    # Determine if an existing zone_settings row exists.
    lsb_zones = load_lsb_zones(root)
    existing_row = zone_id in lsb_zones

    # Existing enum entry?
    enum_map = load_lsb_zone_enum(root)
    existing_enum = enum_map.get(zone_id)

    # SQL
    sql = _sql_for(zone_id, folder_name, existing_row)

    # Lua paths
    script_dir = root / "scripts" / "zones" / folder_name
    zone_lua_path = script_dir / "Zone.lua"
    ids_lua_path = script_dir / "IDs.lua"

    timestamp = time.strftime("%Y-%m-%d")
    zone_lua = _ZONE_LUA_TEMPLATE.format(
        folder_name=folder_name,
        zone_id=zone_id,
        dat_path=dat_path,
        timestamp=timestamp,
    )
    ids_lua = _IDS_LUA_TEMPLATE.format(folder_name=folder_name, enum_name=enum_name)

    enum_patch_line = f"    {enum_name:<32s}= {zone_id},"

    # GM warp helper. Server-side `!exec` runs lua against the calling GM.
    gm_warp = f"!exec player:setPos(0, 0, 0, 0, {zone_id})"

    # Write Lua files if requested.
    existing_dirs = existing_zone_script_dirs(root)
    folder_exists = folder_name in existing_dirs
    written: list[str] = []
    if apply:
        if folder_exists:
            click.echo(click.style(
                f"WARNING: scripts/zones/{folder_name}/ already exists; not overwriting.",
                fg="yellow"))
        else:
            script_dir.mkdir(parents=True, exist_ok=True)
            zone_lua_path.write_text(zone_lua, encoding="utf-8", newline="\n")
            ids_lua_path.write_text(ids_lua, encoding="utf-8", newline="\n")
            written.extend([str(zone_lua_path.relative_to(root)),
                           str(ids_lua_path.relative_to(root))])

    return {
        "zone_id":         zone_id,
        "folder_name":     folder_name,
        "enum_name":       enum_name,
        "dat_path":        dat_path,
        "existing_row":    existing_row,
        "existing_enum":   existing_enum,
        "folder_exists":   folder_exists,
        "sql":             sql,
        "zone_lua":        zone_lua,
        "ids_lua":         ids_lua,
        "enum_patch_line": enum_patch_line,
        "gm_warp":         gm_warp,
        "written":         written,
    }


@click.command("stage")
@click.argument("zone_id", type=int)
@click.option("--name", "pretty_name", required=True,
              help='Human name e.g. "Den of Rancor" — also used for folder + enum.')
@click.option("--apply", is_flag=True,
              help="Write Lua skeleton files. SQL is always printed (never auto-run).")
def cmd(zone_id, pretty_name, apply):
    """Generate LSB scaffolding for a recovered zone.

    By default this is a dry run — everything is printed, nothing is written.
    Pass --apply to write the Lua skeleton to disk. SQL is never auto-applied;
    you run it yourself when you're ready.
    """
    result = stage(zone_id, pretty_name, apply)

    click.echo(click.style(f"\n=== Zone {result['zone_id']}  ({result['folder_name']}) ===", fg="green"))
    click.echo(f"  DAT          : {result['dat_path']}")
    click.echo(f"  Existing row : {'yes (will UPDATE)' if result['existing_row'] else 'no  (will INSERT)'}")
    click.echo(f"  Existing enum: {result['existing_enum'] or 'none — patch enum/zone.lua manually'}")
    click.echo(f"  Folder exists: {'YES — skipped' if result['folder_exists'] else 'no'}")

    click.echo(click.style("\n-- SQL (paste into a migration or run via `mysql`) --", fg="cyan"))
    click.echo(result["sql"])

    if not result["existing_enum"]:
        click.echo(click.style("-- Enum patch (add to scripts/enum/zone.lua, keep numerically sorted) --",
                               fg="cyan"))
        click.echo(result["enum_patch_line"])
        click.echo()

    click.echo(click.style("-- GM in-game verification --", fg="cyan"))
    click.echo(f"  {result['gm_warp']}")
    click.echo()

    if apply and result["written"]:
        click.echo(click.style("-- Written --", fg="green"))
        for p in result["written"]:
            click.echo(f"  {p}")
    elif not apply:
        click.echo(click.style(
            "-- Dry run — pass --apply to write Lua skeleton. SQL still printed above for you to run. --",
            fg="yellow"))
