"""``xi zone make-template <source_zone>`` — package a hand-curated zone into a
reusable template bundle.

Curate a zone in the editor (set weather, clean VFX), Publish it, then freeze it here.
Captures all four zone DATs (zone, event, dialog, npc) and the zone's DB settings into
a bundle folder under ``xi-tools-workspaces/templates/<id>/``.

Source zone must be a custom zone (id >= 400). To template an original FFXI zone,
Duplicate it first (File ▸ Package Changes ▸ Duplicate Zone), then template the copy.
"""

from __future__ import annotations

import json
import secrets
import shutil
from datetime import datetime, timezone
from pathlib import Path

import click

from xi.entity.anim.xi_export import parse_sections
from xi.ftable.xi_core import load_all_tables, scan_file_ids
from xi.xi_config import FFXI_DIR
from xi.zone.xi_inject import (
    zone_model_file_id, zone_event_file_id, zone_dialog_file_id, zone_npc_file_id,
)


def _resolve_zone_dat(file_id: int, from_output: bool) -> tuple[Path, str] | tuple[None, None]:
    """file_id → (path, rel). Returns (None, None) if not registered or not on disk."""
    hits = scan_file_ids([file_id], load_all_tables())
    if not hits:
        return None, None
    rel = hits[0]["dat"]
    dat = Path(FFXI_DIR) / rel
    if not from_output:
        # Pristine snapshot: prefer the <dat>.base backup taken on first edit.
        base = dat.with_name(dat.name + ".base")
        if base.is_file():
            return base, rel
    return (dat, rel) if dat.is_file() else (None, rel)


def _zone_kind(data: bytes) -> dict:
    """Structural summary used to warn about non-outdoor sources."""
    secs = parse_sections(data)
    types = {s.type_code for s in secs}
    n36 = sum(1 for s in secs if s.type_code == 0x36)
    stack, has_weat_env = [], False
    for s in secs:
        nm = data[s.start:s.start + 4].decode("ascii", "replace").rstrip("\x00")
        if s.type_code == 0x01:
            stack.append(nm)
        elif s.type_code == 0x00 and stack:
            stack.pop()
        elif s.type_code == 0x2F and "weat" in stack:
            has_weat_env = True
    return {"sky": has_weat_env, "n36": n36, "is_zone": 0x1C in types and 0x2E in types}


def _sql_val(v) -> str:
    """Format a Python value as a SQL literal."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, (bytes, bytearray)):
        return "X'" + bytes(v).hex() + "'"
    return "'" + str(v).replace("'", "''") + "'"


def _write_data_sql(source_zone: int, tdir: Path) -> tuple[bool, str]:
    """Query live DB for source_zone's zone_settings + zone_weather, write data.sql.

    The SQL uses ``?ZONE_ID?``, ``?ZONE_NAME?``, ``?ZONE_IP?``, ``?ZONE_PORT?``
    as placeholders — substituted when ``zone new`` stamps a new zone from this template.
    Returns (ok, message)."""
    try:
        import pymysql
        from xi.xi_config import db_creds
        conn = pymysql.connect(**db_creds(), charset="utf8mb4",
                               autocommit=True, connect_timeout=4)
    except Exception as e:
        return False, f"DB unavailable: {e}"
    try:
        with conn.cursor() as cur:
            cols = ("zonetype", "music_day", "music_night", "battlesolo",
                    "battlemulti", "restriction", "tax", "misc")
            col_list = ", ".join(f"`{c}`" for c in cols)
            cur.execute(
                f"SELECT {col_list} FROM zone_settings WHERE zoneid=%s", (source_zone,))
            row = cur.fetchone()
            if not row:
                return False, f"zone {source_zone} not found in zone_settings"
            vals = ", ".join(_sql_val(v) for v in row)

            cur.execute("SELECT weather FROM zone_weather WHERE zone=%s", (source_zone,))
            wrow = cur.fetchone()

        lines = [
            f"-- Template DB data for zone {source_zone}",
            f"-- Placeholders: ?ZONE_ID? ?ZONE_NAME? ?ZONE_IP? ?ZONE_PORT?",
            f"-- Generated by `xi zone make-template`",
            f"",
            f"DELETE FROM `zone_settings` WHERE zoneid = ?ZONE_ID?;",
            f"INSERT INTO `zone_settings`",
            f"  (zoneid, zoneip, zoneport, name, {', '.join(cols)})",
            f"  VALUES (?ZONE_ID?, '?ZONE_IP?', ?ZONE_PORT?, '?ZONE_NAME?', {vals});",
            f"",
            f"DELETE FROM `zone_weather` WHERE zone = ?ZONE_ID?;",
        ]
        if wrow and wrow[0]:
            lines.append(
                f"INSERT INTO `zone_weather` (zone, weather)"
                f" VALUES (?ZONE_ID?, X'{wrow[0].hex()}');")

        (tdir / "data.sql").write_text("\n".join(lines) + "\n", encoding="utf-8")
        return True, "ok"
    except Exception as e:
        return False, str(e)
    finally:
        conn.close()


def make_template(*, source_zone: int, label: str, description: str = "",
                  from_pristine: bool = False, dry_run: bool = False) -> dict:
    """Package a zone into a reusable template bundle.

    Source zone must be >= 400 (custom zone). For original FFXI zones, Duplicate first.
    Shared by the CLI and the editor bridge. Raises ``ValueError`` on bad input.
    Returns a result dict (written files when not dry_run)."""
    if not label.strip():
        raise ValueError("Label is required.")
    if source_zone < 400:
        raise ValueError(
            f"Zone {source_zone} is an original FFXI zone (id < 400). "
            "Duplicate it first (File ▸ Package Changes ▸ Duplicate Zone), "
            "then make a template from the copy.")

    use_output = not from_pristine
    zone_fid = zone_model_file_id(source_zone)
    zone_path, zone_rel = _resolve_zone_dat(zone_fid, use_output)
    if zone_path is None:
        raise ValueError(f"Zone {source_zone} model DAT not found (file_id={zone_fid}).")

    data = zone_path.read_bytes()
    kind = _zone_kind(data)
    if not kind["is_zone"]:
        raise ValueError(f"{zone_rel} doesn't look like a zone DAT (needs 0x1C + 0x2E sections).")

    event_path,  event_rel  = _resolve_zone_dat(zone_event_file_id(source_zone),  use_output)
    dialog_path, dialog_rel = _resolve_zone_dat(zone_dialog_file_id(source_zone), use_output)
    npc_path,    npc_rel    = _resolve_zone_dat(zone_npc_file_id(source_zone),    use_output)

    warnings = []
    if not kind["sky"] or kind["n36"] == 0:
        warnings.append("source has no weat sky / no 0x36 — zones stamped from this may render without sky")
    if event_path is None:
        warnings.append(f"event DAT not found (file_id={zone_event_file_id(source_zone)})")
    if dialog_path is None:
        warnings.append(f"dialog DAT not found (file_id={zone_dialog_file_id(source_zone)})")
    if npc_path is None:
        warnings.append(f"npc DAT not found (file_id={zone_npc_file_id(source_zone)})")

    template_id = secrets.token_hex(3)
    from xi.zone.xi_bridge import workspaces_repo_root
    tdir = workspaces_repo_root() / "templates" / template_id

    result = {
        "id":          template_id,
        "label":       label.strip(),
        "description": description.strip(),
        "source_zone": source_zone,
        "zone_rel":    zone_rel,
        "warnings":    warnings,
        "tdir":        str(tdir),
    }

    if dry_run:
        result["dry_run"] = True
        return result

    tdir.mkdir(parents=True, exist_ok=True)

    shutil.copy2(zone_path, tdir / "zone.dat")
    if event_path:
        shutil.copy2(event_path,  tdir / "event.dat")
    if dialog_path:
        shutil.copy2(dialog_path, tdir / "dialog.dat")
    if npc_path:
        shutil.copy2(npc_path,    tdir / "npc.dat")

    meta: dict = {
        "label":       label.strip(),
        "description": description.strip(),
        "source_zone": source_zone,
        "created":     datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }
    (tdir / "metadata.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")

    db_ok, db_msg = _write_data_sql(source_zone, tdir)
    if not db_ok:
        warnings.append(f"data.sql not written ({db_msg}) — zone new will fall back to live DB clone")
    result["db_ok"] = db_ok
    result["written"] = True
    return result


@click.command("make-template")
@click.argument("source_zone", type=int)
@click.option("--label", required=True,
              help="Display label shown in the editor's New-Zone dropdown.")
@click.option("--description", default="",
              help="Short description saved as template metadata.")
@click.option("--from-pristine", is_flag=True,
              help="Snapshot the pristine <dat>.base backup instead of your edited DAT.")
@click.option("--dry-run", is_flag=True,
              help="Show what would be written without touching files.")
def cmd(source_zone, label, description, from_pristine, dry_run):
    """Package a (hand-cleaned) custom zone (id >= 400) into a reusable ``zone new`` template.

    \b
    Source zone must be a custom zone (id >= 400). To template an original FFXI zone,
    Duplicate it first, then run make-template on the copy.

    \b
    Examples:
      xi zone make-template 401 --label "Snow Template"
      xi zone make-template 402 --label "Sunny Jungle" --description "Bright tropical"
    """
    try:
        r = make_template(source_zone=source_zone, label=label, description=description,
                          from_pristine=from_pristine, dry_run=dry_run)
    except ValueError as e:
        raise click.ClickException(str(e))

    click.echo(f"Source  : zone {r['source_zone']} → {r['zone_rel']}")
    click.echo(f"ID      : {r['id']}")
    click.echo(f"Label   : {r['label']}")
    if r.get("description"):
        click.echo(f"Desc    : {r['description']}")
    for w in r["warnings"]:
        click.echo(click.style(f"  ⚠ {w}", fg="yellow"))

    if r.get("dry_run"):
        click.echo(click.style("Dry run — nothing written.", fg="cyan"))
        return

    click.echo(click.style(f"\n✓ Template '{r['label']}' ({r['id']}) saved → {r['tdir']}", fg="green"))
    if r.get("db_ok"):
        click.echo("  data.sql: zone_settings + zone_weather captured from live DB")
    click.echo(f"  CLI:    xi zone new --template {r['id']} --name \"My Zone\"")
    click.echo("  Editor: File ▸ Package Changes ▸ New Zone → pick from the dropdown.")
