"""``xi zone new`` — stamp out a fresh zone from a template bundle.

Copies the template's four DATs (zone, event, dialog, npc) into
FFXI_DIR/ROM10/2/ and registers them in FTABLE10 with the next free
zone ID (400+).  Templates are hand-curated zones packaged with
``xi zone make-template`` and stored in xi-tools-workspaces/templates/<id>/.

Spawn position is configured server-side (zone_settings); this command only
writes the client DATs.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import click

from xi.ftable.xi_core import load_all_tables
from xi.xi_config import (FFXI_DIR, DB_AUTOAPPLY, DB_HOST, DB_NAME,
                            DB_USER, db_creds)
from xi.zone.xi_inject import (
    _ensure_rom10, _next_free_slot, _next_free_zone_id, zone_model_file_id,
    zone_event_file_id, zone_dialog_file_id, zone_npc_file_id,
    register_zone_file,
)
from xi.entity.anim.xi_export import parse_sections

NEW_SUBDIR = 2


def _templates_root() -> Path:
    """``<workspaces-repo>/templates`` — resolved live so the active project can change."""
    from xi.zone.xi_bridge import workspaces_repo_root   # lazy: avoids import cycle
    return workspaces_repo_root() / "templates"


def resolve_template(template_id: str) -> dict | None:
    """6-char template id → bundle dict, or ``None`` if unknown / missing zone.dat."""
    tdir = _templates_root() / template_id
    meta_path = tdir / "metadata.json"
    if not meta_path.is_file():
        return None
    try:
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
    except Exception:
        return None
    zone_dat = tdir / "zone.dat"
    if not zone_dat.is_file():
        return None
    def _opt(name: str) -> Path | None:
        p = tdir / name
        return p if p.is_file() else None
    return {
        "label":       meta.get("label", template_id),
        "description": meta.get("description", ""),
        "source_zone": meta.get("source_zone"),
        "dat":         zone_dat,
        "event_dat":   _opt("event.dat"),
        "dialog_dat":  _opt("dialog.dat"),
        "npc_dat":     _opt("npc.dat"),
        "data_sql":    _opt("data.sql"),
        "tdir":        tdir,
    }


def all_templates() -> dict:
    """Scan workspaces/templates/*/metadata.json → ``{id: {label, description, indoor, ...}}``."""
    root = _templates_root()
    if not root.is_dir():
        return {}
    out = {}
    for meta_path in sorted(root.glob("*/metadata.json")):
        tmpl = resolve_template(meta_path.parent.name)
        if tmpl is not None:
            out[meta_path.parent.name] = tmpl
    return out


def _zone_migration_sql(zone_id: int, name: str, donor: int,
                        ip: str = "127.0.0.1", port: int = 54230) -> str:
    """SQL to register the custom zone on the dev server by CLONING a donor zone's
    zone_settings + zone_weather (overriding id/name/ip/port). Idempotent."""
    nm = name.replace("'", "''")
    return (
        f"-- zone-migration.sql - register custom zone {zone_id} ({name}) on the dev server.\n"
        f"-- Generated by `xi zone new`. Idempotent (DELETE+INSERT). Clones zone {donor}'s\n"
        f"-- settings + weather so the new zone behaves like that real zone (minus geometry).\n"
        f"\n"
        f"-- 1. zone_settings - clone donor zone {donor}, override id/name/ip/port.\n"
        f"DELETE FROM `zone_settings` WHERE zoneid = {zone_id};\n"
        f"INSERT INTO `zone_settings`\n"
        f"  (zoneid, zonetype, zoneip, zoneport, name, music_day, music_night, battlesolo, battlemulti, restriction, tax, misc)\n"
        f"  SELECT {zone_id}, zonetype, '{ip}', {port}, '{nm}', music_day, music_night, battlesolo, battlemulti, restriction, tax, misc\n"
        f"  FROM `zone_settings` WHERE zoneid = {donor};\n"
        f"\n"
        f"-- 2. zone_weather - clone donor's weather rotation (matches the baked sky).\n"
        f"DELETE FROM `zone_weather` WHERE zone = {zone_id};\n"
        f"INSERT INTO `zone_weather` (zone, weather) SELECT {zone_id}, weather FROM `zone_weather` WHERE zone = {donor};\n"
        f"\n"
        f"-- 3. Server build: ensure MAX_ZONEID >= {zone_id + 1} (patches/zone_max_512.patch) - code, not SQL.\n"
        f"-- 4. Restart the map server + client.\n"
    )


# zone_settings columns a template clones (everything but the per-zone id/ip/port/name).
SETTINGS_CLONE_COLS = ("zonetype", "music_day", "music_night", "battlesolo",
                       "battlemulti", "restriction", "tax", "misc")


def _sql_literal(v) -> str:
    """Quote a Python value for a baked SQL literal."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, (bytes, bytearray)):
        return "X'" + bytes(v).hex() + "'"
    return "'" + str(v).replace("'", "''") + "'"


def _template_migration_sql(data_sql_path: Path, zone_id: int, name: str,
                             ip: str = "127.0.0.1", port: int = 54230) -> str | None:
    """Generate zone-migration.sql from a template bundle's data.sql.

    Substitutes ``?ZONE_ID?``, ``?ZONE_NAME?``, ``?ZONE_IP?``, ``?ZONE_PORT?``
    placeholders with the new zone's values. Returns ``None`` if data.sql missing."""
    if not data_sql_path or not data_sql_path.is_file():
        return None
    sql = data_sql_path.read_text(encoding="utf-8")
    nm = name.replace("'", "''")
    sql = sql.replace("?ZONE_ID?", str(zone_id))
    sql = sql.replace("'?ZONE_IP?'", f"'{ip}'")
    sql = sql.replace("?ZONE_PORT?", str(port))
    sql = sql.replace("'?ZONE_NAME?'", f"'{nm}'")
    return sql


# Marker stamped into every xi-generated server Lua so cleanup (`zone delete`) can
# tell an auto-scaffold apart from a hand-authored zone and never clobber the latter.
_LUA_MARKER = "-- xi: auto-generated server scaffold for a custom zone"


def _ids_lua(zone_id: int, name: str) -> str:
    """Minimal ``IDs.lua`` for a custom zone. The map server runs this in
    ``PopulateIDLookups`` then reads ``zones[zoneId]`` by the NUMERIC id, so we
    index by the literal id — custom zones (400+) have no ``xi.zone.<NAME>``
    constant in scripts/enum/zone.lua to key off."""
    return (
        f"-----------------------------------\n"
        f"-- Area: {name}\n"
        f"{_LUA_MARKER}\n"
        f"-----------------------------------\n"
        f"zones = zones or {{}}\n"
        f"\n"
        f"zones[{zone_id}] =\n"
        f"{{\n"
        f"    text =\n"
        f"    {{\n"
        f"    }},\n"
        f"    mob =\n"
        f"    {{\n"
        f"    }},\n"
        f"    npc =\n"
        f"    {{\n"
        f"    }},\n"
        f"}}\n"
        f"\n"
        f"return zones[{zone_id}]\n"
    )


def _zone_lua(zone_id: int, name: str) -> str:
    """Minimal ``Zone.lua`` so onZoneIn / onInitialize resolve (no cutscene)."""
    return (
        f"-----------------------------------\n"
        f"-- Zone: {name} ({zone_id})\n"
        f"{_LUA_MARKER}\n"
        f"-----------------------------------\n"
        f"---@type TZone\n"
        f"local zoneObject = {{}}\n"
        f"\n"
        f"zoneObject.onInitialize = function(zone)\n"
        f"end\n"
        f"\n"
        f"zoneObject.onZoneIn = function(player, prevZone)\n"
        f"    local cs = -1\n"
        f"    return cs\n"
        f"end\n"
        f"\n"
        f"zoneObject.onEventUpdate = function(player, csid, option, npc)\n"
        f"end\n"
        f"\n"
        f"zoneObject.onEventFinish = function(player, csid, option, npc)\n"
        f"end\n"
        f"\n"
        f"return zoneObject\n"
    )


def write_server_zone_scripts(zone_id: int, zone_name: str) -> str | None:
    """Scaffold ``scripts/zones/<zone_name>/{IDs,Zone}.lua`` under the dev server so
    the map server stops erroring `cannot open scripts/zones/<name>/IDs.lua` for the
    custom zone. The folder name MUST match ``zone_settings.name`` exactly (the
    server derives the path from the zone's name, spaces and all).

    Never overwrites a file that lacks the xi marker (a hand-authored zone).
    Returns a human-readable status string, or ``None`` if no server dir is found.
    """
    from xi.xi_config import server_zone_scripts_dir
    zones_dir = server_zone_scripts_dir()
    if zones_dir is None:
        return None

    zdir = zones_dir / zone_name
    zdir.mkdir(parents=True, exist_ok=True)
    written = []
    for fname, body in (("IDs.lua", _ids_lua(zone_id, zone_name)),
                        ("Zone.lua", _zone_lua(zone_id, zone_name))):
        fpath = zdir / fname
        if fpath.exists() and _LUA_MARKER not in fpath.read_text(encoding="utf-8", errors="replace"):
            continue  # hand-authored — leave it alone
        fpath.write_text(body, encoding="utf-8")
        written.append(fname)
    if not written:
        return f"server scripts: kept existing (hand-authored) {zdir}"
    return f"server scripts: wrote {'+'.join(written)} → scripts/zones/{zone_name}/"


def _split_sql(text: str) -> list[str]:
    """Statements from a SQL script, dropping full-line `--` comments and blanks."""
    body = "\n".join(l for l in text.splitlines() if not l.lstrip().startswith("--"))
    return [s.strip() for s in body.split(";") if s.strip()]


def _apply_migration(sql_text: str) -> int:
    """Run the migration against the dev DB. Returns the number of statements applied.
    Raises on connection/SQL error (caller reports + falls back to the .sql file)."""
    import pymysql
    conn = pymysql.connect(**db_creds(), charset="utf8mb4",
                           autocommit=True, connect_timeout=4)
    n = 0
    try:
        with conn.cursor() as cur:
            for stmt in _split_sql(sql_text):
                cur.execute(stmt)
                n += 1
    finally:
        conn.close()
    return n

# Section type codes
_ENV_TYPE  = 0x2F   # environment / weather / fog
_MESH_TYPE = 0x2E   # zone mesh geometry
_TEX_TYPES = {0x20, 0x21}  # textures + palettes

# Section types to DROP when grafting a source zone's weat/ subtree: weather VFX
# (0x05) and sound (0x3D) — the two the template baking itself strips — plus water
# features (0x25 wasi, 0x3E line). They reference resources that live OUTSIDE the
# weat subtree in the source zone, so transplanting them crashes the client. The
# sky atmosphere (env 0x2F, sky meshes 0x2E, textures 0x20/0x21) carries no such
# external refs and is kept.
_SKY_DROP_TYPES = {0x05, 0x3D, 0x25, 0x3E}

# 4-char section-header prefixes that identify sky/atmosphere meshes.
# The FFXI section header name is the first 4 bytes of each section — a truncated
# version of the internal mesh name.  These cover sun/moon/stars/clouds across
# most outdoor zones (mirrors the isSkyName() prefix list in zone.js).
_SKY_MESH_HDRS = ('sun', 'moon', 'star', 'clod', 'cld', 'clou', 'clo',
                  'kamo', 'suny', 'sora', 'dust', 'sky', 'haze')


def _weat_subtree_range(data: bytes) -> tuple[int, int] | None:
    """Byte range ``[start, end)`` of the first ``weat`` directory subtree — from its
    ``0x01`` dir-open header through its matching ``0x00`` dir-close.

    FFXI DATs are a nested tree: ``0x01`` sections push a 4-char-named directory and
    ``0x00`` sections pop it. Outdoor zones keep their whole weather + sky package
    (environments, sky meshes, their textures, weather VFX) under ``weat/<weather>/``.
    """
    secs = parse_sections(data)
    depth = 0
    start = None
    for s in secs:
        name = data[s.start:s.start + 4].decode('ascii', 'replace').rstrip('\x00')
        if s.type_code == 0x01:
            if start is None and name == 'weat':
                start, depth = s.start, 1
            elif start is not None:
                depth += 1
        elif s.type_code == 0x00 and start is not None:
            depth -= 1
            if depth == 0:
                return start, s.start + s.size
    return None


def _splice_sky(data: bytearray, sky_path: Path,
                include_meshes: bool = True) -> tuple[int, int, int]:
    """Swap the template's ``weat/`` directory subtree for the sky source's.

    The FFXI client only loads outdoor sky/atmosphere data — weather environments
    (0x2F), sun/moon/cloud meshes (0x2E), their textures (0x20/0x21) and weather VFX
    (0x05) — from sections nested under a ``weat/<weather>/`` directory. A real
    outdoor zone keeps all of it under one self-contained ``weat`` subtree.

    The previous approach copied bare 0x2F payloads with no directory wrappers and
    dumped them flat next to the zonedef, so they landed under the zonedef's own dir
    (``…/mode``) with NOTHING under ``weat``. The client then found no weather
    environment and rendered a black sky + treated the zone as indoor (instant
    logout, etc.) — even though the xi editor still drew sky (it keys on mesh
    names, ignoring the env tree). The fix is to lift the *entire* ``weat`` subtree
    from the source and drop it in place of the template's, preserving the
    ``0x01``/``0x00`` directory brackets so the client parents everything correctly.

    To avoid transplanting the source zone's externally-referencing weather VFX /
    sound / water sections (which crash the client), the subtree is rebuilt keeping
    only the directory skeleton (0x01/0x00) and the self-contained sky atmosphere
    (env 0x2F, sky meshes 0x2E, textures 0x20/0x21) — see ``_SKY_DROP_TYPES``.

    ``include_meshes`` is kept for API compatibility; sky meshes are always kept.
    Returns ``(n_env, n_mesh, n_tex)`` brought in.
    """
    sky_data = sky_path.read_bytes()
    sky_weat = _weat_subtree_range(sky_data)
    tmpl_weat = _weat_subtree_range(bytes(data))
    if sky_weat is None:
        raise ValueError(f"No 'weat' directory subtree in sky source {sky_path.name}")
    if tmpl_weat is None:
        raise ValueError("No 'weat' directory subtree in template — cannot place sky")

    new_weat = bytearray()
    n_env = n_mesh = n_tex = 0
    for s in parse_sections(sky_data):
        if not (sky_weat[0] <= s.start < sky_weat[1]):
            continue
        if s.type_code in _SKY_DROP_TYPES:
            continue
        new_weat += sky_data[s.start:s.start + s.size]
        if s.type_code == _ENV_TYPE:    n_env += 1
        elif s.type_code == _MESH_TYPE: n_mesh += 1
        elif s.type_code in _TEX_TYPES: n_tex += 1

    data[tmpl_weat[0]:tmpl_weat[1]] = bytes(new_weat)
    return n_env, n_mesh, n_tex


def _copy_template_companions(zone_id: int, tmpl: dict, subdir: int,
                              rom10_dir: Path, reserved: set) -> list:
    """Copy event/dialog/npc from a template bundle and register them for zone_id.

    Returns ``[(dtype, fid, slot, dst), ...]`` — same shape as clone_zone_companions."""
    pairs = [
        ("event",  zone_event_file_id,  "event_dat"),
        ("dialog", zone_dialog_file_id, "dialog_dat"),
        ("npc",    zone_npc_file_id,    "npc_dat"),
    ]
    out = []
    for dtype, fn, key in pairs:
        src = tmpl.get(key)
        if not src or not src.is_file():
            continue
        tgt_fid = fn(zone_id)
        slot = _next_free_slot(rom10_dir, subdir)
        while slot in reserved:
            slot += 1
        reserved.add(slot)
        dst = rom10_dir / str(subdir) / f"{slot}.DAT"
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        register_zone_file(tgt_fid, subdir, slot)
        out.append((dtype, tgt_fid, slot, dst))
    return out


@click.command("new")
@click.option("--name", "zone_name", default=None, metavar="NAME",
              help="Human-readable zone name saved to zone-meta.json in the workspace.")
@click.option("--template", "template", required=True, metavar="ID",
              help="Template bundle id (6-char hex from `xi zone make-template`).")
@click.option("--sky", "sky_dat", default=None, metavar="DAT",
              help="Pull sky/environment sections (0x2F env + 0x05 VFX) from this DAT "
                   "(ROM-relative path or absolute). Normally not needed — the template "
                   "bundle already carries the sky.")
@click.option("--zone-id", type=int, default=None,
              help="Force a specific zone ID instead of auto-assigning from 400+.")
@click.option("--apply-db/--no-apply-db", "apply_db", default=None,
              help="Apply the generated zone-migration.sql to the dev server DB now. "
                   "Default: follow XI_DB_AUTOAPPLY (applies when the DB is reachable).")
@click.option("--server-scripts/--no-server-scripts", "server_scripts", default=True,
              help="Scaffold scripts/zones/<name>/{IDs,Zone}.lua under the dev server "
                   "(XI_SERVER_DIR). The map server needs IDs.lua or it errors on the "
                   "custom zone at startup. Default: on when a server checkout is found.")
@click.option("--dry-run", is_flag=True,
              help="Show what would be written without touching any files.")
def cmd(zone_name: str | None, template: str, sky_dat: str | None, zone_id: int | None,
        apply_db: bool | None, server_scripts: bool, dry_run: bool):
    """Create a new zone from a template bundle.

    Writes to FFXI_DIR/ROM10/2/<slot> and registers it in FTABLE10.
    Configure the spawn point server-side (zone_settings INSERT).

    \b
    Examples:
      xi zone new --template a3f9kx --name "My Snow Zone"
      xi zone new --template b7qm2r --name "Lost Jungle" --zone-id 450 --dry-run
    """
    tmpl = resolve_template(template)
    if tmpl is None:
        available = ", ".join(all_templates()) or "(none — run `xi zone make-template` first)"
        raise click.ClickException(
            f"Unknown template '{template}'. Available: {available}")

    tables = load_all_tables()
    if zone_id is None:
        zone_id = _next_free_zone_id(tables)

    rom10_dir = Path(FFXI_DIR) / "ROM10"
    slot = _next_free_slot(rom10_dir, NEW_SUBDIR)
    dst = rom10_dir / str(NEW_SUBDIR) / f"{slot}.DAT"
    fid = zone_model_file_id(zone_id)

    click.echo(f"New zone:  ID={zone_id}  →  ROM10/{NEW_SUBDIR}/{slot}.DAT  (file_id={fid})")
    click.echo(f"Template:  {template}  ({tmpl['label']})")
    if sky_dat:
        click.echo(f"Sky:       {sky_dat}")

    if dry_run:
        click.echo(click.style("Dry run — nothing written.", fg="cyan"))
        return

    sky_path: Path | None = None
    if sky_dat:
        from xi.zone.xi_export import resolve_dat_path
        try:
            sky_path = resolve_dat_path(sky_dat)
        except FileNotFoundError as e:
            raise click.ClickException(str(e))

    _ensure_rom10()

    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(tmpl["dat"], dst)

    if sky_path:
        data = bytearray(dst.read_bytes())
        n_env, n_mesh, n_tex = _splice_sky(data, sky_path)
        dst.write_bytes(bytes(data))
        click.echo(f"  Sky:  {n_env} env, {n_mesh} sky mesh(es), {n_tex} texture(s) from {sky_path.name}")

    reserved = {slot}
    register_zone_file(fid, NEW_SUBDIR, slot)
    companions = _copy_template_companions(zone_id, tmpl, NEW_SUBDIR, rom10_dir, reserved)
    if companions:
        click.echo("  Companions: " + ", ".join(
            f"{d}→ROM10/{NEW_SUBDIR}/{sl}" for d, _f, sl, _dst in companions))

    # Write zone-meta.json into the workspace
    import json as _json
    from xi.zone.xi_bridge import _workspace_dir
    resolved_name = (zone_name or "").strip() or f"Zone_{zone_id}"
    dat_url = f"game/ROM10/{NEW_SUBDIR}/{slot}.DAT"
    meta = {"name": resolved_name, "zoneId": zone_id, "fileId": fid, "datUrl": dat_url}
    ws = _workspace_dir(f"ROM10/{NEW_SUBDIR}/{slot}.DAT")
    (ws / "zone-meta.json").write_text(_json.dumps(meta, indent=2), encoding="utf-8")

    # Write the DB migration from the template's data.sql; fall back to live clone.
    mig_sql = _template_migration_sql(tmpl.get("data_sql"), zone_id, resolved_name)
    if mig_sql is None:
        source = tmpl.get("source_zone")
        if source:
            mig_sql = _zone_migration_sql(zone_id, resolved_name, source)
    mig_path = None
    if mig_sql:
        mig_path = ws / "zone-migration.sql"
        mig_path.write_text(mig_sql, encoding="utf-8")

    click.echo(click.style(f"\n✓ Zone {zone_id} ({resolved_name}) created: {dst}", fg="green"))
    click.echo(f"  Metadata:  {ws / 'zone-meta.json'}")
    if mig_path:
        click.echo(f"  Migration: {mig_path}")
    else:
        click.echo(click.style("  DB:        no data.sql in template — register zone_settings manually", fg="yellow"))

    # Auto-apply to the dev DB (clones zone_settings + zone_weather from donor zone).
    do_apply = (DB_AUTOAPPLY if apply_db is None else apply_db) and mig_sql is not None
    applied = False
    if do_apply:
        try:
            n = _apply_migration(mig_sql)
            click.echo(click.style(
                f"  DB:        applied {n} statement(s) to {DB_NAME}@{DB_HOST}", fg="green"))
            applied = True
        except Exception as exc:  # connection refused, pymysql missing, etc.
            click.echo(click.style(f"  DB:        auto-apply skipped ({exc})", fg="yellow"))
            click.echo(f"             apply manually: mysql -u{DB_USER} {DB_NAME} < \"{mig_path}\"")

    # Scaffold the per-zone server Lua (IDs.lua + Zone.lua) — folder name MUST match
    # zone_settings.name (the server derives the path from the zone's name).
    scaffolded = False
    if server_scripts:
        msg = write_server_zone_scripts(zone_id, resolved_name)
        if msg is None:
            click.echo(click.style(
                "  Server:    no dev-server checkout found (set XI_SERVER_DIR) — "
                "IDs.lua NOT written", fg="yellow"))
        else:
            click.echo(click.style(f"  Server:    {msg}", fg="green"))
            scaffolded = True

    click.echo("\nServer-side TODO:")
    if mig_path and not applied:
        click.echo(f"  - Apply the migration: mysql -u{DB_USER} {DB_NAME} < \"{mig_path}\"")
    if not scaffolded:
        click.echo(f"  - Create scripts/zones/{resolved_name}/IDs.lua (+ Zone.lua) on the server")
    click.echo(f"  - Ensure MAX_ZONEID >= {zone_id + 1}  (patches/zone_max_512.patch — server build)")
    click.echo(f"  - Set the spawn point: UPDATE zone_settings ... (x, y, z) for zone {zone_id}")
    click.echo(f"  - Restart map server + client")


@click.command("scaffold-server")
@click.option("--zone-id", type=int, default=None,
              help="Scaffold just this zone ID (default: every custom zone, id >= 400).")
@click.option("--min-id", type=int, default=400, show_default=True,
              help="Lowest zone ID treated as a custom zone to scaffold.")
@click.option("--dry-run", is_flag=True, help="List what would be written, touch nothing.")
def scaffold_server_cmd(zone_id: int | None, min_id: int, dry_run: bool):
    """Backfill the per-zone server Lua (scripts/zones/<name>/{IDs,Zone}.lua) for
    custom zones already registered in the dev DB.

    The map server requires scripts/zones/<name>/IDs.lua for every zone it loads,
    deriving the folder name from zone_settings.name. `xi zone new` now writes
    this automatically; run this to fix zones created before that — it stops the
    `cannot open scripts/zones/<name>/IDs.lua` startup errors.

    \b
    Examples:
      xi zone scaffold-server                 # all custom zones (400+)
      xi zone scaffold-server --zone-id 401
    """
    from xi.xi_config import XI_SERVER_DIR, server_zone_scripts_dir

    if server_zone_scripts_dir() is None:
        raise click.ClickException(
            f"No dev-server scripts/zones found (XI_SERVER_DIR={XI_SERVER_DIR!r}). "
            "Set XI_SERVER_DIR to your server checkout root.")

    try:
        import pymysql
        conn = pymysql.connect(**db_creds(), charset="utf8mb4", connect_timeout=4)
    except Exception as exc:
        raise click.ClickException(f"Cannot reach the dev DB to list zones: {exc}")

    try:
        with conn.cursor() as cur:
            if zone_id is not None:
                cur.execute("SELECT zoneid, name FROM zone_settings WHERE zoneid = %s", (zone_id,))
            else:
                cur.execute("SELECT zoneid, name FROM zone_settings WHERE zoneid >= %s "
                            "ORDER BY zoneid", (min_id,))
            rows = cur.fetchall()
    finally:
        conn.close()

    if not rows:
        click.echo("No matching custom zones in zone_settings.")
        return

    for zid, name in rows:
        name = (name or "").strip() or f"Zone_{zid}"
        if dry_run:
            click.echo(f"  would scaffold {zid}: scripts/zones/{name}/")
            continue
        msg = write_server_zone_scripts(zid, name)
        click.echo(f"  {zid}: {msg}")
    if dry_run:
        click.echo(click.style("Dry run — nothing written.", fg="cyan"))
