import os
import re
import shutil
import click
from xi.xi_config import (FFXI_DIR, XI_TOOLS_DIR, CUSTOM_ROM, CUSTOM_ROM_IDX,
                            output_path_for, read_path_for)
from xi.ftable.xi_core import patch_table
from xi.entity.xi_core import (
    MODEL_FILE_OFFSET, MODEL_SAFE_START, MODEL_SAFE_END, modelid_blob
)

ROM_TARGET   = CUSTOM_ROM
ROM_IDX      = CUSTOM_ROM_IDX
CUSTOM_SUBDIR = 1

FTABLE_TOTAL = MODEL_SAFE_END + MODEL_FILE_OFFSET + 1


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _check_expansion():
    # Check the expanded tables in the output mirror (where `ftable expand` wrote).
    ft10 = read_path_for(os.path.join(FFXI_DIR, ROM_TARGET, f'FTABLE{ROM_IDX}.DAT'))
    if not os.path.exists(ft10):
        raise click.ClickException(
            f'{ROM_TARGET}/FTABLE{ROM_IDX}.DAT not found. Run "xi ftable expand entity" first.')
    actual = os.path.getsize(ft10) // 2
    if actual < FTABLE_TOTAL:
        raise click.ClickException(
            f'{ROM_TARGET}/FTABLE{ROM_IDX}.DAT has {actual} entries but needs {FTABLE_TOTAL}. '
            f'Re-run "xi ftable expand entity {MODEL_SAFE_END}".')
    base_ft = read_path_for(os.path.join(FFXI_DIR, 'FTABLE.DAT'))
    base_entries = os.path.getsize(base_ft) // 2
    if base_entries < FTABLE_TOTAL:
        raise click.ClickException(
            f'FTABLE.DAT has {base_entries} entries but needs {FTABLE_TOTAL}. '
            f'Re-run "xi ftable expand entity".')


def _get_occupied_file_ids() -> set:
    from xi.ftable.xi_core import load_tables
    occupied = set()
    for idx in range(1, 11):
        tables = load_tables(idx)
        if not tables:
            continue
        fdata, vdata = tables
        safe_start = MODEL_SAFE_START + MODEL_FILE_OFFSET
        for fid in range(safe_start, min(len(vdata), FTABLE_TOTAL)):
            if vdata[fid] != 0:
                occupied.add(fid)
    return occupied


def _find_free_model_id(occupied: set, requested) -> int:
    if requested is not None:
        fid = requested + MODEL_FILE_OFFSET
        if fid in occupied:
            raise click.ClickException(
                f'modelid {requested} is already occupied (file_id={fid}). '
                f'Run without --modelid to auto-assign.')
        if not (MODEL_SAFE_START <= requested <= MODEL_SAFE_END):
            raise click.ClickException(
                f'modelid {requested} is out of safe range ({MODEL_SAFE_START}-{MODEL_SAFE_END}).')
        return requested
    for mid in range(MODEL_SAFE_START, MODEL_SAFE_END + 1):
        if (mid + MODEL_FILE_OFFSET) not in occupied:
            return mid
    raise click.ClickException('No free monster-model slots in the safe range.')


def _get_next_rom10_slot(start_subdir: int = CUSTOM_SUBDIR):
    # Injected custom DATs live in the output mirror — scan there for free slots.
    base   = str(output_path_for(os.path.join(FFXI_DIR, ROM_TARGET)))
    subdir = start_subdir
    while True:
        target_dir = os.path.join(base, str(subdir))
        if not os.path.exists(target_dir):
            return subdir, 0
        dats = sorted(f for f in os.listdir(target_dir) if f.upper().endswith('.DAT'))
        if len(dats) < 128:
            return subdir, len(dats)
        subdir += 1


def _generate_sql(modelid, file_id, rom_path, pool_id, pet_id, pet_name, species_id):
    blob    = modelid_blob(modelid)
    lua_key = pet_name.upper().replace(' ', '_').replace('-', '_')
    return f"""\
-- ============================================================
--  Custom Entity Model Injection
--  Generated by xi monster inject
-- ------------------------------------------------------------
--  modelid  : {modelid} (0x{modelid:04X})
--  file_id  : {file_id}
--  rom_path : {rom_path}
-- ============================================================

-- Step 1: mob_pools
INSERT INTO `mob_pools` VALUES (
  {pool_id},                           -- poolid
  'Custom_Model_{modelid}',            -- internal_name
  'Custom_Model_{modelid}',            -- display_name
  {species_id},                        -- speciesid (114 = tiger family)
  {blob}, -- modelid blob
  1, 1,                                -- mJob, sJob
  7, 240, 100,                         -- modelSize, cmbDelay
  0, 0, 0, 0,                          -- slash/pierce/h2h/impact sdt
  8, 0, 0, 395, 131,                   -- magic/fire/ice/wind/earth sdt
  0, 0, 0, 0, 0,                       -- lightning/water/light/dark sdt, name_prefix
  735, 242,                            -- skill_list_id, resist_id
  0, 25                                -- modelHitboxSize, hasSpellScript
);

-- Step 2: pet_list
INSERT INTO `pet_list` VALUES (
  {pet_id},          -- petid
  '{pet_name}',      -- name (max 15 chars)
  {pool_id},         -- poolid
  28, 40,            -- minLevel, maxLevel
  3600,              -- despawn (seconds)
  0,                 -- element
  3                  -- damageType
);

-- Step 3: Lua enum  (server/scripts/enum/pet_id.lua)
--   xi.pet.id.{lua_key} = {pet_id}

-- Step 4: Spawn
--   xi.pet.spawnPet(player, xi.pet.id.{lua_key})
"""


# ---------------------------------------------------------------------------
# Click command
# ---------------------------------------------------------------------------

@click.command('inject')
@click.argument('dat_file')
@click.option('--modelid',           type=int,  default=None,
              help=f'Model ID to register (default: auto, safe range {MODEL_SAFE_START}-{MODEL_SAFE_END})')
@click.option('--pool-id',           type=int,  default=None,
              help='mob_pools.poolid (default: modelid + 10000)')
@click.option('--pet-id',            type=int,  default=None,
              help='pet_list.petid (default: modelid + 200)')
@click.option('--pet-name',          type=str,  default=None,
              help='Pet name for SQL, max 15 chars (default: Custom_<modelid>)')
@click.option('--species',           type=int,  default=114,  show_default=True,
              help='speciesid for mob_pools')
@click.option('--subdir',            type=int,  default=CUSTOM_SUBDIR, show_default=True,
              help=f'{ROM_TARGET} subdir to place the DAT in')
@click.option('--register-existing', is_flag=True,
              help=f'DAT already in {ROM_TARGET} - skip copy, parse dir/file from path')
@click.option('--dry-run',           is_flag=True,
              help='Simulate without writing any files')
def cmd(dat_file, modelid, pool_id, pet_id, pet_name, species, subdir, register_existing, dry_run):
    """Inject a custom entity model DAT (monster, NPC, or object) into the custom ROM and register it in the FTABLE/VTABLE."""
    dat_file = os.path.abspath(dat_file)
    if not os.path.exists(dat_file):
        raise click.ClickException(f'DAT file not found: {dat_file}')

    if not dry_run:
        _check_expansion()

    click.echo('[*] Scanning FTABLE/VTABLE files for occupied slots ...')
    occupied = _get_occupied_file_ids()
    modelid  = _find_free_model_id(occupied, modelid)
    file_id  = modelid + MODEL_FILE_OFFSET

    # Resolve destination
    if register_existing:
        rom10_root = os.path.normcase(os.path.normpath(str(output_path_for(os.path.join(FFXI_DIR, ROM_TARGET)))))
        abs_dat    = os.path.normcase(os.path.normpath(dat_file))
        if not abs_dat.startswith(rom10_root):
            raise click.ClickException(
                f'--register-existing requires the DAT to be inside {ROM_TARGET}/. Got: {dat_file}')
        rel   = os.path.relpath(abs_dat, rom10_root)
        parts = re.split(r'[\\/]', rel)
        if len(parts) != 2:
            raise click.ClickException(f'Expected {ROM_TARGET}/<dir>/<file>.DAT, got: {rel}')
        try:
            subdir   = int(parts[0])
            file_idx = int(os.path.splitext(parts[1])[0])
        except ValueError:
            raise click.ClickException(f'Dir and file must be integers, got: {parts}')
        dest_dat = dat_file
        dest_dir = os.path.dirname(dat_file)
    else:
        subdir, file_idx = _get_next_rom10_slot(subdir)
        dest_dir = str(output_path_for(os.path.join(FFXI_DIR, ROM_TARGET, str(subdir))))
        dest_dat = os.path.join(dest_dir, f'{file_idx}.DAT')

    ftable_val = (subdir << 7) | file_idx
    vtable_val = ROM_IDX
    rom_path   = f'{ROM_TARGET}/{subdir}/{file_idx}.DAT'

    ft10 = os.path.join(FFXI_DIR, ROM_TARGET, f'FTABLE{ROM_IDX}.DAT')
    vt10 = os.path.join(FFXI_DIR, ROM_TARGET, f'VTABLE{ROM_IDX}.DAT')

    pool_id  = pool_id  if pool_id  else modelid + 10000
    pet_id   = pet_id   if pet_id   else modelid + 200
    pet_name = pet_name if pet_name else f'Custom_{modelid}'
    if len(pet_name) > 15:
        click.echo(f'WARNING: --pet-name "{pet_name}" exceeds 15 chars and will be truncated.',
                   err=True)
        pet_name = pet_name[:15]

    patches_dir = os.path.join(XI_TOOLS_DIR, 'patches')
    sql_path    = os.path.join(patches_dir, f'ffxi_dat_ftable_inject_{modelid}_{file_id}.sql')

    click.echo()
    click.echo('=' * 62)
    click.echo('  FFXI Custom Entity Model Injector')
    click.echo('=' * 62)
    click.echo(f'  Input DAT      : {dat_file}')
    click.echo(f'  Destination    : {dest_dat}')
    click.echo(f'  ROM Path       : {rom_path}')
    click.echo()
    click.echo(f'  Model ID       : {modelid}  (0x{modelid:04X})')
    click.echo(f'  File ID        : {file_id}')
    click.echo()
    click.echo(f'  FTABLE10 entry : 0x{ftable_val:04X}  (dir={subdir} << 7 | file={file_idx})')
    click.echo(f'  VTABLE10 entry : {vtable_val}  (ROM{vtable_val})')
    click.echo()
    click.echo(f'  mob_blob       : {modelid_blob(modelid)}')
    click.echo(f'  pool_id        : {pool_id}')
    click.echo(f'  pet_id         : {pet_id}')
    click.echo(f'  pet_name       : {pet_name}')
    click.echo(f'  species_id     : {species}')
    click.echo()
    click.echo(f'  SQL output     : {sql_path}')
    click.echo(f'  Dry run        : {dry_run}')
    click.echo('=' * 62)

    if dry_run:
        click.echo('\n[DRY RUN] Nothing written.')
        return

    if register_existing:
        click.echo(f'\n[+] DAT exists   -> {dest_dat}  (--register-existing, skipping copy)')
    else:
        os.makedirs(dest_dir, exist_ok=True)
        shutil.copy2(dat_file, dest_dat)
        click.echo(f'\n[+] DAT copied   -> {dest_dat}')

    patch_table(ft10, vt10, file_id, ftable_val, vtable_val)
    click.echo(f'[+] FTABLE10 patched @ byte offset {file_id*2} (0x{file_id*2:05X})')
    click.echo(f'[+] VTABLE10 patched @ byte offset {file_id} (0x{file_id:05X})')

    os.makedirs(patches_dir, exist_ok=True)
    sql_content = _generate_sql(modelid, file_id, rom_path, pool_id, pet_id, pet_name, species)
    with open(sql_path, 'w', encoding='utf-8') as f:
        f.write(sql_content)
    click.echo(f'[+] SQL written  -> {sql_path}')

    click.echo()
    click.echo('  Next steps:')
    click.echo(f'    1. Import {os.path.basename(sql_path)} into your LSB database')
    click.echo(f'    2. Add  xi.pet.id.{pet_name.upper().replace(" ","_")} = {pet_id}')
    click.echo(f'       to  server/scripts/enum/pet_id.lua')
    click.echo(f'    3. Call xi.pet.spawnPet(player, {pet_id}) in your BST script')
    click.echo(f'    4. Restart map server')
    click.echo()
    click.echo('[*] Done.')
